### ISSUE TITLE
Add screenshots to README

### ISSUE THREAD

**Issue by naveenkumarsangi** [NITDgpOS/PiZilla#34]

**Comment by pranay414** [comment]
@nkprince007 I would like to take up this. Can you please elaborate on what to do?

**Comment by naveenkumarsangi** [comment]
Run Pizilla locally and capture some screenshots for publishing. Then add them to the readme using the .github/assets folder.

**Comment by naveenkumarsangi** [comment]
Closed via 
https://github.com/NITDgpOS/PiZilla/commit/45fae9682addb7ea7555cd9e593efde3a6697965
