### ISSUE TITLE
README: Add link to gitter chat

### ISSUE THREAD

**Issue by naveenkumarsangi** [NITDgpOS/PiZilla#36]
Add link to Gitter chat: 

```[![Join the chat at https://gitter.im/NIT-dgp/General](https://badges.gitter.im/NIT-dgp/General.svg)](https://gitter.im/NIT-dgp/General?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)```

**Comment by charan7386** [comment]
I'd like to work on this.
