### ISSUE TITLE
Fix spelling mistakes in README

### ISSUE THREAD

**Issue by naveenkumarsangi** [NITDgpOS/PiZilla#44]
Mistakes:
- [ ] `Piilla` to `PiZilla` (Ref: https://github.com/NIT-dgp/PiZilla/blob/master/README.md#configuring-piilla-)
- [ ] `stat` to `start` (Ref: https://github.com/NIT-dgp/PiZilla/commit/f55e7115f054964cf52cc859067efe15301bc15c#diff-04c6e90faac2675aa89e2176d2eec7d8R40)

**Comment by caro401** [comment]
Hi, I would like to fix this please

**Comment by nkprince007** [comment]
Uhm.. it's currently reserved for one of our college events, sorry.

We'll let you know when it begins. 😊

**Comment by naveenkumarsangi** [comment]
Fixed by https://github.com/NITDgpOS/PiZilla/commit/6b30a28927017cb2e5cadc409e26731f9d467270
